# Generated by Django 2.1.7 on 2022-04-06 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220406_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 6, 17, 13, 32, 454991)),
        ),
    ]
